// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDkXu132zgjQMEjL61RnVs04-ACdT5zNFM',
    appId: '1:849751322035:web:6fca230792b7ee222befc6',
    messagingSenderId: '849751322035',
    projectId: 'riftboundtracker',
    authDomain: 'riftboundtracker.firebaseapp.com',
    storageBucket: 'riftboundtracker.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAdkLZTLGNPdA-A9WkQ3YHPYc_98mGkSbc',
    appId: '1:849751322035:android:7c773775877834dd2befc6',
    messagingSenderId: '849751322035',
    projectId: 'riftboundtracker',
    storageBucket: 'riftboundtracker.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBA0F6N5YwPQVlM8aFOCV4pgKplHsy42Tw',
    appId: '1:849751322035:ios:c5cb1d68d4bf4b4b2befc6',
    messagingSenderId: '849751322035',
    projectId: 'riftboundtracker',
    storageBucket: 'riftboundtracker.firebasestorage.app',
    iosBundleId: 'com.example.monApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBA0F6N5YwPQVlM8aFOCV4pgKplHsy42Tw',
    appId: '1:849751322035:ios:c5cb1d68d4bf4b4b2befc6',
    messagingSenderId: '849751322035',
    projectId: 'riftboundtracker',
    storageBucket: 'riftboundtracker.firebasestorage.app',
    iosBundleId: 'com.example.monApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDkXu132zgjQMEjL61RnVs04-ACdT5zNFM',
    appId: '1:849751322035:web:81663e21708b42102befc6',
    messagingSenderId: '849751322035',
    projectId: 'riftboundtracker',
    authDomain: 'riftboundtracker.firebaseapp.com',
    storageBucket: 'riftboundtracker.firebasestorage.app',
  );
}
